### PR TITLE
generate position independent code

### PR DESCRIPTION
**Pull request by hoinmic**
By generating position independent code, the library is more reusable.

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Thanks for your contribution!

I have a few change requests, though:
 - please send as patch to the mailing list (see https://github.com/siemens/efibootguard/blob/master/CONTRIBUTING.md)
 - if you are targeting the libebgenv.a, you want to extend `libebgenv_a_CFLAGS`, not the common `AM_CFLAGS`
 - please avoid `feat` as tag - this project is typically tagging subsystems, not classifying commits

**Comment by hoinmic** [comment]
- Good idea. Flags only adapted to the library.
- Removed "feat" from commit and merge request.

**Comment by hoinmic** [comment]
- oh i missed the first point. unfortunately i am allergic to "patch mailing lists". It will probably take a while until I find the motivation to do this in a github project with "pull requests " :-)

**Comment by jan-kiszka** [comment]
Well, I can reflect simple first-time contributions sent as PR to the list in order to ensure process compliance. I don't want such patches to get lost because of this. But if you want to work with multiple communities in the future, I would recommend getting familiar with other workflows as well.

However, I can't fix another thing I missed on the first run: Your signed-off has to be added, again see CONTRIBUTING.md.

**Comment by hoinmic** [comment]
Done. My git send-email is now fixed :-)

**Comment by jan-kiszka** [comment]
Thanks for the reminder, just forgot to push next->master.

**Pull request closed without merging**
